import { Poppins } from "next/font/google";

import RootStyleRegistry from "./emotion";
import AuthProvider from "@/context/AuthProvider";
import { TopicProvider } from "@/context/TopicContext";
import { ModalProvider } from "@/context/ModalContext";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RootStyleRegistry>
          <AuthProvider>
            <TopicProvider>
              <ModalProvider>{children}</ModalProvider>
            </TopicProvider>
          </AuthProvider>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
